import { GLTF } from 'three-stdlib'
import * as THREE from 'three'

export type GLTFResult = GLTF & {
  nodes: {
    Argent2: THREE.Mesh
    Argent3: THREE.Mesh
    Argent4: THREE.Mesh
    Argent5: THREE.Mesh
    Argent6: THREE.Mesh
    Boite001: THREE.Mesh
    Boite1001: THREE.Mesh
    Boite2001: THREE.Mesh
    Boite3001: THREE.Mesh
    BoiteCarton001: THREE.Mesh
    BoiteCarton1001: THREE.Mesh
    BoiteCarton2001: THREE.Mesh
    BoiteCarton3001: THREE.Mesh
    BoiteCarton4001: THREE.Mesh
    BoiteCarton5001: THREE.Mesh
    BoiteCarton6001: THREE.Mesh
    BoiteCarton7: THREE.Mesh
    BoiteCarton8: THREE.Mesh
    Etagere001: THREE.Mesh
    Boite: THREE.Mesh
    Boite1: THREE.Mesh
    Boite2: THREE.Mesh
    Boite3: THREE.Mesh
    BoiteCarton: THREE.Mesh
    BoiteCarton1: THREE.Mesh
    BoiteCarton2: THREE.Mesh
    BoiteCarton3: THREE.Mesh
    BoiteCarton4: THREE.Mesh
    BoiteCarton5: THREE.Mesh
    BoiteCarton6: THREE.Mesh
    Etagere: THREE.Mesh
    BacBrosse: THREE.Mesh
    Balais: THREE.Mesh
    Bouteille: THREE.Mesh
    Bouteille1: THREE.Mesh
    Bouteille2: THREE.Mesh
    Bouteille6: THREE.Mesh
    Bouteille7: THREE.Mesh
    Bouteille8: THREE.Mesh
    Bouteille9: THREE.Mesh
    Caisse001: THREE.Mesh
    Caisse1: THREE.Mesh
    Caisse2: THREE.Mesh
    Caisse3: THREE.Mesh
    Caisse4: THREE.Mesh
    Caisse5: THREE.Mesh
    CaisseArme001: THREE.Mesh
    CaisseArme1: THREE.Mesh
    CaisseArme2: THREE.Mesh
    CouvercleCArme: THREE.Mesh
    CouvercleCArme1: THREE.Mesh
    CouvercleCArme2: THREE.Mesh
    Fusil_assault1: THREE.Mesh
    Fusil_assault2: THREE.Mesh
    Fusil_assault3: THREE.Mesh
    Fusil_assault4: THREE.Mesh
    Fusil_assault5: THREE.Mesh
    Fusil_assault6: THREE.Mesh
    Fusil_assault7: THREE.Mesh
    Fusil_assault8: THREE.Mesh
    Canapé: THREE.Mesh
    Canette: THREE.Mesh
    Canette1: THREE.Mesh
    Canette10: THREE.Mesh
    Canette2: THREE.Mesh
    Canette3: THREE.Mesh
    Canette4: THREE.Mesh
    Canette5: THREE.Mesh
    Canette6: THREE.Mesh
    Canette7: THREE.Mesh
    Canette8: THREE.Mesh
    Canette9: THREE.Mesh
    Cendrier: THREE.Mesh
    Cendrier1: THREE.Mesh
    Cigarette: THREE.Mesh
    Cigarette1: THREE.Mesh
    Cigarette2: THREE.Mesh
    Cigarette3: THREE.Mesh
    Cuisine1: THREE.Mesh
    DoorWay1: THREE.Mesh
    DoorWay2: THREE.Mesh
    DoorWay3: THREE.Mesh
    DoorWay4: THREE.Mesh
    DoorWay5: THREE.Mesh
    Ecran001: THREE.Mesh
    Ecran1: THREE.Mesh
    Ecran2: THREE.Mesh
    Ecran3: THREE.Mesh
    Ecran4: THREE.Mesh
    Ecran5: THREE.Mesh
    Ecran6: THREE.Mesh
    Ecran7: THREE.Mesh
    FirstAidKit: THREE.Mesh
    FirstAidKit1: THREE.Mesh
    Fusil_assault: THREE.Mesh
    Fusil_assault10: THREE.Mesh
    Fusil_assault11: THREE.Mesh
    Fusil_assault9: THREE.Mesh
    CoffreCoffre: THREE.Mesh
    CoffrePorteBas: THREE.Mesh
    CoffrePorteHaut: THREE.Mesh
    CoffreSerruredroite: THREE.Mesh
    CoffreSerrureGauche: THREE.Mesh
    Photo: THREE.Mesh
    Photo5: THREE.Mesh
    Photo1: THREE.Mesh
    Photo10: THREE.Mesh
    HoloSupport: THREE.Mesh
    Globe: THREE.Mesh
    Neon: THREE.Mesh
    Neon1: THREE.Mesh
    Neon10: THREE.Mesh
    Neon11: THREE.Mesh
    Neon12: THREE.Mesh
    Neon13: THREE.Mesh
    Neon14: THREE.Mesh
    Neon3: THREE.Mesh
    Neon5: THREE.Mesh
    Neon6: THREE.Mesh
    Neon7: THREE.Mesh
    Neon8: THREE.Mesh
    Neon9: THREE.Mesh
    LampeALerte: THREE.Mesh
    Coussin003: THREE.Mesh
    Couverture003: THREE.Mesh
    Coussin002: THREE.Mesh
    Couverture002: THREE.Mesh
    Coussin001: THREE.Mesh
    Couverture001: THREE.Mesh
    Coussin: THREE.Mesh
    Couverture: THREE.Mesh
    Minibar: THREE.Mesh
    Panneau_control: THREE.Mesh
    PaquetCiga: THREE.Mesh
    PaquetCiga1: THREE.Mesh
    Photo2: THREE.Mesh
    Photo3: THREE.Mesh
    Photo4: THREE.Mesh
    Photo6: THREE.Mesh
    Photo7: THREE.Mesh
    Photo9: THREE.Mesh
    Pistolet: THREE.Mesh
    Pistolet2: THREE.Mesh
    Pizza: THREE.Mesh
    PlateauRepas: THREE.Mesh
    pPlane1: THREE.Mesh
    Robinet1: THREE.Mesh
    Room_Room: THREE.Mesh
    Safe1: THREE.Mesh
    Safe2: THREE.Mesh
    Sofa001: THREE.Mesh
    SupportArme: THREE.Mesh
    SupportArme1: THREE.Mesh
    Argent: THREE.Mesh
    Argent1: THREE.Mesh
    Bouteille3: THREE.Mesh
    Bouteille4: THREE.Mesh
    Bouteille5: THREE.Mesh
    HoloSupport_mission: THREE.Mesh
    MissionHolo: THREE.Mesh
    MissionHolo1: THREE.Mesh
    Pistolet1: THREE.Mesh
    PlateauRepas1: THREE.Mesh
    Table001: THREE.Mesh
    Tablette2: THREE.Mesh
    Tabouret001: THREE.Mesh
    Tabouret1: THREE.Mesh
    Tabouret2: THREE.Mesh
    Tabouret3: THREE.Mesh
    Tabouret4: THREE.Mesh
    verre2: THREE.Mesh
    verre3: THREE.Mesh
    TableBasse: THREE.Mesh
    TableBasse1: THREE.Mesh
    Tablette001: THREE.Mesh
    Tablette3: THREE.Mesh
    Tablette4: THREE.Mesh
    Tiroir: THREE.Mesh
    Tiroir1: THREE.Mesh
    Tiroir2: THREE.Mesh
    Tiroir3: THREE.Mesh
    Tiroir4: THREE.Mesh
    Tiroir5: THREE.Mesh
    Tuyau: THREE.Mesh
    Tuyau1: THREE.Mesh
    Tuyau2: THREE.Mesh
    Tuyau3: THREE.Mesh
    Tuyau4: THREE.Mesh
    Tuyau5: THREE.Mesh
    Tuyau6: THREE.Mesh
    Brosseadent: THREE.Mesh
    Brosseadent1: THREE.Mesh
    Verre1: THREE.Mesh
    WetFloor: THREE.Mesh
    Bras: THREE.Mesh
    Robot001: THREE.Mesh
    Fumer: THREE.Mesh
  }
  materials: {
    Objet3: THREE.MeshStandardMaterial
    Objet2: THREE.MeshStandardMaterial
    Objet: THREE.MeshStandardMaterial
    ['Coffre:Texture']: THREE.MeshStandardMaterial
    Room1: THREE.MeshStandardMaterial
    Robot1: THREE.MeshStandardMaterial
  }
}

export type ActionName =
  | 'Fusil_assault10|Take 001|BaseLayer'
  | 'Globe|Take 001|BaseLayer'
  | 'Safe2|Take 001|BaseLayer'
  | 'MissionHolo|Take 001|BaseLayer'
  | 'MissionHolo1|Take 001|BaseLayer'
  | 'Robot|Take 001|BaseLayer'
  | 'Fumer|Take 001|BaseLayer'
