/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, {useRef} from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Mesh_3: THREE.Mesh;
    Mesh_4: THREE.Mesh;
    Mesh_5: THREE.Mesh;
    Mesh_6: THREE.Mesh;
    Mesh_7: THREE.Mesh;
    Mesh_8: THREE.Mesh;
    Mesh_9: THREE.Mesh;
    Mesh_10: THREE.Mesh;
    Mesh_11: THREE.Mesh;
    Mesh_12: THREE.Mesh;
    Mesh_13: THREE.Mesh;
    Mesh_14: THREE.Mesh;
    Mesh_15: THREE.Mesh;
    Mesh_16: THREE.Mesh;
    Mesh_17: THREE.Mesh;
    Mesh_18: THREE.Mesh;
    Mesh_19: THREE.Mesh;
    Mesh_20: THREE.Mesh;
    Mesh_21: THREE.Mesh;
    Mesh_22: THREE.Mesh;
    Mesh_23: THREE.Mesh;
    Mesh_24: THREE.Mesh;
    Mesh_25: THREE.Mesh;
    Mesh_26: THREE.Mesh;
    Mesh_27: THREE.Mesh;
    Mesh_28: THREE.Mesh;
    Mesh_29: THREE.Mesh;
    Mesh_30: THREE.Mesh;
    Mesh_31: THREE.Mesh;
    Mesh_32: THREE.Mesh;
    Mesh_33: THREE.Mesh;
    Mesh_34: THREE.Mesh;
    Mesh_35: THREE.Mesh;
    Mesh_36: THREE.Mesh;
    Mesh_37: THREE.Mesh;
    Mesh_38: THREE.Mesh;
    Mesh_39: THREE.Mesh;
    Mesh_40: THREE.Mesh;
    Mesh_41: THREE.Mesh;
    Mesh_42: THREE.Mesh;
    Mesh_43: THREE.Mesh;
    Mesh_44: THREE.Mesh;
    Mesh_45: THREE.Mesh;
    Mesh_46: THREE.Mesh;
    Mesh_47: THREE.Mesh;
    Mesh_48: THREE.Mesh;
    Mesh_49: THREE.Mesh;
    Mesh_50: THREE.Mesh;
    Mesh_51: THREE.Mesh;
    Mesh_52: THREE.Mesh;
    Mesh_53: THREE.Mesh;
    Mesh_54: THREE.Mesh;
    Mesh_55: THREE.Mesh;
    Mesh_56: THREE.Mesh;
    Mesh_57: THREE.Mesh;
    Mesh_58: THREE.Mesh;
    Mesh_59: THREE.Mesh;
    Mesh_60: THREE.Mesh;
    Mesh_61: THREE.Mesh;
    Mesh_62: THREE.Mesh;
    Mesh_63: THREE.Mesh;
    Mesh_64: THREE.Mesh;
    Mesh_65: THREE.Mesh;
    Mesh_66: THREE.Mesh;
    Mesh_67: THREE.Mesh;
    Mesh_68: THREE.Mesh;
    Mesh_69: THREE.Mesh;
    Mesh_70: THREE.Mesh;
    Mesh_71: THREE.Mesh;
    Mesh_72: THREE.Mesh;
    Mesh_73: THREE.Mesh;
    Mesh_74: THREE.Mesh;
    Mesh_75: THREE.Mesh;
    Mesh_76: THREE.Mesh;
    Mesh_77: THREE.Mesh;
    Mesh_78: THREE.Mesh;
    Mesh_79: THREE.Mesh;
    Mesh_80: THREE.Mesh;
    Mesh_81: THREE.Mesh;
    Mesh_82: THREE.Mesh;
    Mesh_83: THREE.Mesh;
    Mesh_84: THREE.Mesh;
    Mesh_85: THREE.Mesh;
    Mesh_86: THREE.Mesh;
    Mesh_87: THREE.Mesh;
    Mesh_88: THREE.Mesh;
    Mesh_89: THREE.Mesh;
    Mesh_90: THREE.Mesh;
    Mesh_91: THREE.Mesh;
    Mesh_92: THREE.Mesh;
    Mesh_93: THREE.Mesh;
  };
  materials: {
    ["sci_fi_yep__2_:sci_fi_wall1:main_wall_colour"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:x_on_wall"]: THREE.MeshStandardMaterial;
    lambert2: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:Floor_main_base"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:floor_second"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:floor_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:Floor_side_secondary"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:Floor_side_main"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:Floor_side_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall2:Floor_main_base"]: THREE.MeshStandardMaterial;
    lambert3: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:Floor_side_main1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:Floor_side_third1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:Floor_side_secondary1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:floor_second1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:floor_third1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall2:Floor_side_main"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall2:Floor_side_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall2:Floor_side_secondary"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_4:sci_fi_wall1:main_wall_colour"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_4:sci_fi_wall1:x_on_wall"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:triangle_bits_on_the_window"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:lights2"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:main_wall_colour2"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:space_wall2"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:bottom_of_box2"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:side_box_cude2"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:details_on_box2"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall:main_wall_colour"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall:lights"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:details_on_box3"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall1:main_wall_colour"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:main_wall_colour3"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall1:bottom_of_box"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall1:space_wall"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall1:side_box_cude"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall1:details_on_box"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall1:lights"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall1:x_on_wall"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall2:main_wall_colour"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_5:sci_fi_wall1:main_wall_colour3"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall2:bottom_of_box"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall2:space_wall"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall2:side_box_cude"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall2:details_on_box"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall2:lights"]: THREE.MeshStandardMaterial;
    ["sci_fi_wall2:x_on_wall"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall:main_wall_colour1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:lights4"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall:lights1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:details_on_box4"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_:sci_fi_wall1:space_wall4"]: THREE.MeshStandardMaterial;
    pasted__lambert4: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_8:sci_fi_wall1:Floor_main_base"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_8:sci_fi_wall1:floor_second"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_8:sci_fi_wall1:floor_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_8:sci_fi_wall1:Floor_side_secondary"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_8:sci_fi_wall1:Floor_side_main"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_8:sci_fi_wall1:Floor_side_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_9:sci_fi_wall1:main_wall_colour"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_9:sci_fi_wall1:space_wall"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_9:sci_fi_wall1:lights"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_9:sci_fi_wall1:x_on_wall"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_9:sci_fi_wall1:bottom_of_box"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_9:sci_fi_wall1:side_box_cude"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_9:sci_fi_wall1:details_on_box"]: THREE.MeshStandardMaterial;
    lambert4: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall1:floor_second"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall1:floor_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall1:Floor_side_main"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall1:Floor_side_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall1:Floor_side_secondary"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall2:floor_second"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall2:floor_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall2:Floor_side_secondary"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall2:Floor_side_main"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall2:Floor_side_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__1_:sci_fi_wall1:Floor_main_base"]: THREE.MeshStandardMaterial;
    pasted__pasted__lambert4: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_10:sci_fi_wall1:Floor_main_base"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_10:sci_fi_wall1:floor_second"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_10:sci_fi_wall1:floor_third"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_10:sci_fi_wall1:Floor_side_secondary"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_10:sci_fi_wall1:Floor_side_main"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_10:sci_fi_wall1:Floor_side_third"]: THREE.MeshStandardMaterial;
    pasted__pasted__box_shaped_thing_on_other_main_wall: THREE.MeshStandardMaterial;
    pasted__pasted__triangle_shaped_thing_on_box_on_wall: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_11:sci_fi_wall1:main_wall_colour1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_11:sci_fi_wall1:space_wall1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_11:sci_fi_wall1:lights1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_11:sci_fi_wall1:x_on_wall1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_11:sci_fi_wall1:bottom_of_box1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_11:sci_fi_wall1:side_box_cude1"]: THREE.MeshStandardMaterial;
    ["sci_fi_yep__2_11:sci_fi_wall1:details_on_box1"]: THREE.MeshStandardMaterial;
  };
};

interface ShipProps {
  position: [number, number, number]
  rotation: [number, number, number]
  scale: number
}

const ShipInteriors = ({position, rotation, scale}: ShipProps) => {
  const { nodes, materials } = useGLTF("/models/ship_interiors.gltf") as unknown as GLTFResult;

  // Ship interiors reference
  const shipRef = useRef<any>()
  return (
    <group ref={shipRef} name="shipinteriors" position={position} rotation={rotation} scale={scale}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:main_wall_colour"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_1.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:x_on_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_2.geometry}
          material={materials.lambert2}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_3.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:Floor_main_base"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_4.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:floor_second"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_5.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:floor_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_6.geometry}
          material={
            materials["sci_fi_yep__2_:sci_fi_wall1:Floor_side_secondary"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_7.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:Floor_side_main"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_8.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:Floor_side_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_9.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall2:Floor_main_base"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_10.geometry}
          material={materials.lambert3}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_11.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:Floor_side_main1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_12.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:Floor_side_third1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_13.geometry}
          material={
            materials["sci_fi_yep__2_:sci_fi_wall1:Floor_side_secondary1"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_14.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:floor_second1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_15.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:floor_third1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_16.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall2:Floor_side_main"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_17.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall2:Floor_side_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_18.geometry}
          material={
            materials["sci_fi_yep__2_:sci_fi_wall2:Floor_side_secondary"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_19.geometry}
          material={materials["sci_fi_yep__2_4:sci_fi_wall1:main_wall_colour"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_20.geometry}
          material={materials["sci_fi_yep__2_4:sci_fi_wall1:x_on_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_21.geometry}
          material={materials["sci_fi_yep__2_:triangle_bits_on_the_window"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_22.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:lights2"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_23.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:main_wall_colour2"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_24.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:space_wall2"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_25.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:bottom_of_box2"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_26.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:side_box_cude2"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_27.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:details_on_box2"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_28.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall:main_wall_colour"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_29.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall:lights"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_30.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:details_on_box3"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_31.geometry}
          material={materials["sci_fi_wall1:main_wall_colour"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_32.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:main_wall_colour3"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_33.geometry}
          material={materials["sci_fi_wall1:bottom_of_box"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_34.geometry}
          material={materials["sci_fi_wall1:space_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_35.geometry}
          material={materials["sci_fi_wall1:side_box_cude"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_36.geometry}
          material={materials["sci_fi_wall1:details_on_box"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_37.geometry}
          material={materials["sci_fi_wall1:lights"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_38.geometry}
          material={materials["sci_fi_wall1:x_on_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_39.geometry}
          material={materials["sci_fi_wall2:main_wall_colour"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_40.geometry}
          material={materials["sci_fi_yep__2_5:sci_fi_wall1:main_wall_colour3"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_41.geometry}
          material={materials["sci_fi_wall2:bottom_of_box"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_42.geometry}
          material={materials["sci_fi_wall2:space_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_43.geometry}
          material={materials["sci_fi_wall2:side_box_cude"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_44.geometry}
          material={materials["sci_fi_wall2:details_on_box"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_45.geometry}
          material={materials["sci_fi_wall2:lights"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_46.geometry}
          material={materials["sci_fi_wall2:x_on_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_47.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall:main_wall_colour1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_48.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:lights4"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_49.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall:lights1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_50.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:details_on_box4"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_51.geometry}
          material={materials["sci_fi_yep__2_:sci_fi_wall1:space_wall4"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_52.geometry}
          material={materials.pasted__lambert4}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_53.geometry}
          material={materials["sci_fi_yep__2_8:sci_fi_wall1:Floor_main_base"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_54.geometry}
          material={materials["sci_fi_yep__2_8:sci_fi_wall1:floor_second"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_55.geometry}
          material={materials["sci_fi_yep__2_8:sci_fi_wall1:floor_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_56.geometry}
          material={
            materials["sci_fi_yep__2_8:sci_fi_wall1:Floor_side_secondary"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_57.geometry}
          material={materials["sci_fi_yep__2_8:sci_fi_wall1:Floor_side_main"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_58.geometry}
          material={materials["sci_fi_yep__2_8:sci_fi_wall1:Floor_side_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_59.geometry}
          material={materials["sci_fi_yep__2_9:sci_fi_wall1:main_wall_colour"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_60.geometry}
          material={materials["sci_fi_yep__2_9:sci_fi_wall1:space_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_61.geometry}
          material={materials["sci_fi_yep__2_9:sci_fi_wall1:lights"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_62.geometry}
          material={materials["sci_fi_yep__2_9:sci_fi_wall1:x_on_wall"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_63.geometry}
          material={materials["sci_fi_yep__2_9:sci_fi_wall1:bottom_of_box"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_64.geometry}
          material={materials["sci_fi_yep__2_9:sci_fi_wall1:side_box_cude"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_65.geometry}
          material={materials["sci_fi_yep__2_9:sci_fi_wall1:details_on_box"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_66.geometry}
          material={materials.lambert4}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_67.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall1:floor_second"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_68.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall1:floor_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_69.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall1:Floor_side_main"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_70.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall1:Floor_side_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_71.geometry}
          material={
            materials["sci_fi_yep__1_:sci_fi_wall1:Floor_side_secondary"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_72.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall2:floor_second"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_73.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall2:floor_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_74.geometry}
          material={
            materials["sci_fi_yep__1_:sci_fi_wall2:Floor_side_secondary"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_75.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall2:Floor_side_main"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_76.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall2:Floor_side_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_77.geometry}
          material={materials["sci_fi_yep__1_:sci_fi_wall1:Floor_main_base"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_78.geometry}
          material={materials.pasted__pasted__lambert4}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_79.geometry}
          material={materials["sci_fi_yep__2_10:sci_fi_wall1:Floor_main_base"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_80.geometry}
          material={materials["sci_fi_yep__2_10:sci_fi_wall1:floor_second"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_81.geometry}
          material={materials["sci_fi_yep__2_10:sci_fi_wall1:floor_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_82.geometry}
          material={
            materials["sci_fi_yep__2_10:sci_fi_wall1:Floor_side_secondary"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_83.geometry}
          material={materials["sci_fi_yep__2_10:sci_fi_wall1:Floor_side_main"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_84.geometry}
          material={materials["sci_fi_yep__2_10:sci_fi_wall1:Floor_side_third"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_85.geometry}
          material={
            materials.pasted__pasted__box_shaped_thing_on_other_main_wall
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_86.geometry}
          material={
            materials.pasted__pasted__triangle_shaped_thing_on_box_on_wall
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_87.geometry}
          material={
            materials["sci_fi_yep__2_11:sci_fi_wall1:main_wall_colour1"]
          }
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_88.geometry}
          material={materials["sci_fi_yep__2_11:sci_fi_wall1:space_wall1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_89.geometry}
          material={materials["sci_fi_yep__2_11:sci_fi_wall1:lights1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_90.geometry}
          material={materials["sci_fi_yep__2_11:sci_fi_wall1:x_on_wall1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_91.geometry}
          material={materials["sci_fi_yep__2_11:sci_fi_wall1:bottom_of_box1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_92.geometry}
          material={materials["sci_fi_yep__2_11:sci_fi_wall1:side_box_cude1"]}
        />
        <mesh
          castShadow={true}
          receiveShadow={true}
          geometry={nodes.Mesh_93.geometry}
          material={materials["sci_fi_yep__2_11:sci_fi_wall1:details_on_box1"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ship_interiors.gtlf");

export default ShipInteriors;
